version: '3'

volumes:
  postgres-data:

services:
#  django:
#    build:
#      context: .
#    depends_on:
#      - postgres
#    volumes:
#      - ./:/app
#    ports:
#      - "8000:8000"

  postgres:
    restart: always
    image: postgres:14
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=test
    ports:
      - "5444:5432"