# Generated by Django 4.1.7 on 2023-03-27 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=250)),
                ('subject', models.CharField(max_length=250)),
                ('time_from', models.CharField(max_length=10)),
                ('time_to', models.CharField(max_length=10)),
                ('room', models.CharField(max_length=10)),
            ],
        ),
    ]
